### ISSUE TITLE
Issues when issueing cake build

### ISSUE THREAD

**Issue by owlowlgo** [pwnall/dropship-chrome#10]
Hello pwnall,

I tried building the project via your instructions, but it always fails at the following point. 

```
user@PC MINGW64 ~/xxx/dropship-chrome (master)
$ cake build
'node_modules\uglify-js\bin\uglifyjs' ▒́A▒▒▒▒▒R▒}▒▒▒h▒܂▒▒͊O▒▒▒R▒}▒▒▒h▒A
▒▒▒▒\▒ȃv▒▒▒O▒▒▒▒▒܂▒▒̓o▒b▒` ▒t▒@▒C▒▒▒Ƃ▒▒ĔF▒▒▒▒▒▒Ă▒▒܂▒▒▒B
Non-zero exit code 1 running
    node_modules\uglify-js\bin\uglifyjs --compress --mangle --output vendor\js\humanize.min.js vendor\js\humanize.js

user@PC MINGW64 ~/xxx/dropship-chrome (master)
$

```

I was able to build the project by manually installing uglifyjs globally and removing the --mangle --compress(uglifyjs would choke on those as well), but wondering what you think of this situation. Sorry if it's a newbie mistake on my part.

Thank you.

**Comment by pwnall** [comment]
@owlowlgo FWIW, I just cloned the repo on OSX and tried all the steps, and things seem to work for me.

`--mangle` is a valid UglifyJS option documented [here](https://github.com/mishoo/UglifyJS2#mangler-options).
`--compress` is also a valid option documented [here](https://github.com/mishoo/UglifyJS2#compressor-options).

I would guess UglifyJS doesn't work well in Windows, and I don't support Windows either. I'd recommend getting a proper UNIX build environment (linux / osx) or hoping that the [Windows 10 linux subsystem](http://arstechnica.com/information-technology/2016/03/ubuntus-bash-and-linux-command-line-coming-to-windows-10/) will make things better in the future.

Sorry I can't help you more.

**Comment by owlowlgo** [comment]
@pwnall Thanks for looking into this for me. I guess I'll dev on my linux PC instead then.

**Comment by pwnall** [comment]
@owlowlgo I'm glad you have access to a Linux environment! Please let me know if things break there, I would like things to work on Linux and OSX.
